LORE-139 Add initial Jenkinsfile
connexta/ion-transformation-service-registry pull request #2
Opened 2019-06-10 13:05 UTC by mdang8

#### What does this PR do?
Adds a Jenkinsfile for the CI pipeline.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
 @cjlange 
 @josephthweatt
 @brendan-hofmann
 @figliold
 @mcalcote

#### How should this be tested? (List steps with links to updated documentation)
1. Navigate to the Connexta Jenkins site
2. Go to the `ion-transformation-service-registry` Jenkins job
3. Run a build and verify that it succeeds

#### Any background context you want to provide?

#### What are the relevant tickets?
LORE-139

#### Screenshots (if appropriate)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

2019-06-10 14:51 UTC, brendan-hofmann requested changes

2019-06-10 14:51 UTC, brendan-hofmann commented on Jenkinsfile
> +            steps {
You need to call `dockerd{}` as the first step here if you're building dockerfiles.

2019-06-10 19:23 UTC, brendan-hofmann approved these changes

2019-06-10 19:31 UTC, josephthweatt approved these changes

2019-06-11 17:15 UTC, cjlange approved these changes

2019-06-11 17:44 UTC, figliold approved these changes

2019-06-11 20:06 UTC, merged